@testset "Generic Likelihood" begin
    # Test that an autogenerated dsitribution matches the hand coded one
    @augmodel(AugLaplace, Regression, 0.5 / β, 0, y^2, 2*y, 1, exp(-sqrt(x)/β), -exp(-sqrt(x)/β) / (2β * sqrt(x)), β=2.0)
    d = AugLaplace(;β=2.0)
    l = LaplaceLikelihood(2.0)
    x = rand(10)
    y = rand(10)
    k = SqExponentialKernel()
    @test d(x[1], y[1]) ≈ l(x[1], y[1])
    md = VGP(x, y, k, d, AnalyticVI())
    ml = VGP(x, y, k, l, AnalyticVI())
end