using Test, AugmentedGaussianProcesses

@testset "Generic Likelihood" begin
    # Test that an autogenerated dsitribution matches the hand coded one
    @augmodel(AugLaplace, Regression, 0.5 / β, 0, y^2, 2*y, 1, exp(-sqrt(x)/β), β=2.0)
    d = AugLaplace(;β=2.0)
    l = LaplaceLikelihood(2.0)
    x = rand(10)
    y = rand(10)
    k = SqExponentialKernel()
    @test d(x[1], y[1]) ≈ l(x[1], y[1])
    md = VGP(x, y, k, d, AnalyticVI(); optimiser=false)
    ml = VGP(x, y, k, l, AnalyticVI(); optimiser=false)
    d = md.likelihood
    l = ml.likelihood
    aopt = AGP.AVIOptimizer{Float64}(1, Descent())
    @test md.likelihood.θ == ml.likelihood.θ
    @test length(md.likelihood.c²) == length(ml.likelihood.b)
    @test loglikelihood(d, y[1], x[1]) ≈ loglikelihood(l, y[1], x[1])
    @test AGP.∇E_μ(d, aopt, y) == AGP.∇E_μ(l, aopt, y)
    @test AGP.∇E_Σ(d, aopt, y) == AGP.∇E_Σ(l, aopt, y)
    @show mean(pω(d, 0.1))
    @show var(pω(d, 0.1))

    train!(md, 100)
    train!(ml, 100)
end